# Generated by Django 6.1.1 on 2026-09-17 03:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, help_text='Unique institution student identifier (e.g., STU-2024-001)', max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(db_index=True, help_text='Official student email address', max_length=254, unique=True)),
                ('phone', models.CharField(max_length=25)),
                ('department', models.CharField(choices=[('Computer Science & Engineering', 'Computer Science & Engineering'), ('Data Science & AI', 'Data Science & AI'), ('Information Technology', 'Information Technology'), ('Electrical & Electronics', 'Electrical & Electronics'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Biotechnology', 'Biotechnology'), ('Business Administration', 'Business Administration')], max_length=80)),
                ('year_of_study', models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], default=1)),
                ('gpa', models.DecimalField(decimal_places=2, help_text='Cumulative Grade Point Average (0.00 - 4.00)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)])),
                ('enrollment_status', models.CharField(choices=[('Active', 'Active'), ('Graduated', 'Graduated'), ('On Leave', 'On Leave'), ('Suspended', 'Suspended')], default='Active', max_length=20)),
                ('enrollment_date', models.DateField()),
                ('address', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student_id'], name='students_st_student_e7126a_idx'), models.Index(fields=['email'], name='students_st_email_e271bc_idx'), models.Index(fields=['department'], name='students_st_departm_c67345_idx'), models.Index(fields=['enrollment_status'], name='students_st_enrollm_7bd618_idx')],
            },
        ),
    ]
